config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]

  get 'courses/:id/resume' => 'courses#resume'
  resources :courses

  resources :joins, only: [:index, :new, :create]

  resources :messages, only: [:create, :update, :destroy]
  resources :replies, only: [:create, :update, :destroy]

  root "courses#index"

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :user_courses
  has_many :users, through: :user_courses

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :replies
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :message
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_courses
  has_many :joins
  has_many :courses, through: :user_courses
  has_many :messages
  has_many :replies
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image_url])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image_url])
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  # require 'net/http'
  # require 'net/https'
  # require 'uri'

  def resume

    @course = Course.find(params[:id])

    url = URI.parse(@course.resume);

    res = Net::HTTP.start(url.host, url.port) { |http|
      http.get(url.path)
    }

    @response = res.body

    render text: @response
  end

  def index

  end

  def show
    # TODO: そのユーザーのperrmissionを検査(そのcourseに属しているか調査)

    @course = Course.find(params[:id])

    @reply = Reply.new
    @message = Message.new
    @messages = Message.where(course_id: params[:id])
    @votes = []

    @messages.each do |message|
      @votes[message.id] = []
      @votes[message.id][0] = Reply.where(['message_id = ? and value = ?', message.id, 0])
      @votes[message.id][1] = Reply.where(['message_id = ? and value = ?', message.id, 1])

      @reply_id = params[:reply]
    end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save then

      UserCourse.create(user_id: current_user.id, course_id: @course.id)

      redirect_to @course
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params) then

      UserCourse.create(user_id: current_user.id, course_id: @course.id)

      redirect_to @course
    end
  end

  def destroy
  end

  private

  def course_params
    params.require(:course).permit(:name, :permission, :resume)
  end

end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  def index
  end

  def new
    @join = Join.new
    @courses = Course.all
  end

  def create
    data = join_params
    data[:user_id] = current_user.id

    @join = Join.new(data)
    @join.save

    result = UserCourse.where(['user_id = ? and course_id = ?', data[:user_id], data[:course_id]])

    # 重複して参加しないようにする処理
    if(result.count == 0) then
      @user_course = UserCourse.new(data)
      @user_course.save
    end

    redirect_to course_path(data[:course_id])
  end

  private

  def join_params
    params.require(:join).permit(:course_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    data = message_params
    data[:user_id] = current_user.id

    @message = Message.new(data)

    if @message.save then
      redirect_to course_path(@message.course_id)
    end
  end

  def update
  end

  def destroy
    # TODO : 削除のpermissionが存在するかどうかcheck
    @message = Message.find(params[:id])
    @message.destroy

    # TODO: 直接アクセスされた場合の処理
    # http://qiita.com/azusanakano/items/8af1266f53a656ef787d
    redirect_to :back
  end

  private

  def message_params
    params.require(:message).permit(:body, :course_id, :attr)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    data = reply_params
    data[:user_id] = current_user.id

    @reply = Reply.new(data)

    if @reply.save then
      redirect_to :back
    end

  end

  def update
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    redirect_to :back
  end

  private

  def reply_params
    params.require(:reply).permit(:body, :message_id, :value)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <fieldset>

    <div class="form-group">
      <%= f.label :name, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Course Name '%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :permission, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.number_field :permission, class: 'form-control', placeholder: 'Permission '%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :resume, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :resume, class: 'form-control', placeholder: 'Resume URL'  %>
      </div>
    </div>
  </fieldset>

  <%= f.submit "Create", class: 'btn btn-primary' %>

<% end %>

app/views/courses/edit.html.erb
<%= render partial: 'form' %>

app/views/courses/index.html.erb
  <section class="course-index">
    <h3>Choose Your Course</h3>
    <%= render template: 'joins/new' %>
    <%= link_to 'or create new course.', new_course_path, class: 'pull-right' %>
  </section>

app/views/courses/new.html.erb
   <div class="container">
      <div class="panel panel-primary">
        <div class="panel-heading">New Course</div>

        <div class="panel-body">
          <%= render partial: 'form' %>
        </div>
      </div>
  </div>

app/views/courses/resume.html.erb
<%= @response %>

app/views/courses/show.html.erb
<div class="row course-top" style="text-align: center; height: 200px; background: #ddd; line-height: 200px;">

<object data="/courses/<%= @course.id %>/resume" style="width: 100%; height: 100%;"></object>

</div>

<div class="row">

  <div class="col-sm-9" style="border:1px solid #eee; text-align:center">

    <div class="panel panel-success row">
      <div class="panel-heading">
        <h3 class="panel-title">Communication</h3>
      </div>
      <div class="panel-body">

        <% @messages.each do |message| %>

          <div class="media course-message" style="border: 1px solid #ddd;">
            <div class="media-left">
              <a href="/users/<%= message.user_id %>">
                <img class="media-object" src="<%= message.user.image_url %>" alt="message.user.name" style="width: 50px; height: 50px;">
             </a>
          </div>
          <div class="media-body">
            <div class="row">
              <div class="col-sm-11">

                <h4 class="media-heading"><a href="/users/<%= message.user_id %>"><%= message.user.name %></a></h4>

              </div>
              <div class="col-sm-1">
                  <i class="glyphicon glyphicon-option-vertical dropdown-toggle" id="messageMenu<%= message.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></i>

                  <ul class="dropdown-menu" aria-labelledby="messageMenu<%= message.id %>">
                    <li class="reply-button" data-id="<%= message.id %>"><p>返信</p></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to '削除', message_path(message.id), method: :delete %></li>
                  </ul>
              </div>
            </div>
            <%= simple_format message.body %>
            <% if message.attr then %>
              <h5>Results</h5>
              <ul>
                <li>Yes : <%= @votes[message.id][1].count %></li>
                <li>No : <%= @votes[message.id][0].count %></li>
              </ul>
            <% end %>

          </div>
          </div>

          <% # 選択肢がある場合(attr == true)の処理 %>
          <% if message.attr then %>
            <%= form_for(@reply, url: { controller: :replies, action: :create}) do |f| %>
              <div>
              <%= f.text_field :message_id, type: 'hidden', value: message.id %>
              Yes : <%= f.radio_button :value, '1' %>
              No : <%= f.radio_button :value, '0' %>
              <%= f.submit "投票", class: "btn btn-primary btn-xs" %>
              </div>
            <% end %>
          <% end %>

          <% message.replies.each do |reply| %>
            <% if !reply.value %>

                <!-- 返信  -->

                <div class="media course-message reply-message" style="margin-left: 60px;border: 1px solid #ddd;">
                    <div class="media-left">
                      <a href="/users/<%= reply.user_id %>">
                        <img class="media-object" src="<%= reply.user.image_url %>" alt="reply.name" style="width: 30px; height: 30px;">
                     </a>
                  </div>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-sm-11">

                        <h4 class="media-heading"><a href="/users/<%= reply.user_id %>"><%= reply.user.name %></a></h4>
                      </div>
                      <div class="col-sm-1">
                          <i class="glyphicon glyphicon-option-vertical dropdown-toggle" id="replyMenu<%= reply.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></i>

                          <ul class="dropdown-menu" aria-labelledby="replyMenu<%= reply.id %>">
                            <li><%= link_to '削除', reply_path(reply.id), method: :delete %></li>
                          </ul>
                      </div>
                    </div>
                    <%= simple_format reply.body %>
                  </div>
                  </div>

                <!-- end  返信  -->

            <% end %>
          <% end %>

          <!-- Send Reply Form -->

                <div class="media course-message reply-message reply-form" style="margin-left: 60px;border: 1px solid #ddd;" id="reply-form<%= message.id %>">
                    <div class="media-left">
                      <a href="/users/<%= current_user.id %>">
                        <img class="media-object" src="<%= current_user.image_url %>" alt="<%=current_user.name%>" style="width: 30px; height: 30px;">
                     </a>
                  </div>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-sm-11">

                        <h4 class="media-heading"><a href="/users/<%= current_user.id %>"><%= current_user.name %></a></h4>
                      </div>

                       <div class="col-sm-1">
                          <i class="glyphicon glyphicon-remove" id="remove_button"></i>
                      </div>

                    </div>

                    <%= form_for(@reply, url: { controller: :replies, action: :create}) do |f| %>
                      <%= f.text_area :body, class: 'form-control', style: 'border: 1px solid #ddd;' %>
                      <%= f.text_field :message_id, type: 'hidden', value: message.id %>
                      <%= f.submit "返信", class: 'btn btn-primary btn-xs' %>
                    <% end %>


                  </div>
                  </div>


          <!-- End Send reply  -->

         <% end %>
      </div><!-- end panel-body -->
    </div><!-- end panel -->
  </div><!-- col-sm-8-->

  <div class="col-sm-2 col-sm-offset-1 members">
    <div class="panel panel-info row">
        <div class="panel-heading">
          <h3 class="panel-title">Members</h3>
        </div>
        <div class="panel-body">
          <ul class="list-group">
            <% @course.users.each do |user| %>
              <li class="list-group-item"><%= link_to user.name, user %></li>
            <% end %>
          </ul>
        </div>
    </div>
    <%= link_to "Edit Course", edit_course_path(@course), class: 'btn btn-link' %>
  </div>
</div>

<footer class="comment-form">
    <%= form_for(@message, url: { controller: :messages, action: :create}) do |f|  %>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-1">
          <%= f.text_field :body, class: 'form-control white' %>
        </div>
        <div class="col-sm-2" id="toggle-button">
          <%= f.check_box 'attr' %>
        </div>
        <%= f.text_field :course_id, value: @course.id, type: 'hidden' %>
        <div class="col-sm-1">
          <%= f.submit "Send!" , class: 'btn btn-info'%>
        </div>
      </div>
    <% end %>
</footer>

<script>
  $("[name='message[attr]']").bootstrapSwitch();
  $("[name='message[attr]']").bootstrapSwitch('onText', 'Vote!');
  $("[name='message[attr]']").bootstrapSwitch('offText', 'Plain');

  $(function() {
    $('.reply-button').click(function() {
      console.log('fnit');
      id = $(this).data('id');

      $('#reply-form' + id).show();
    })
  })

</script>

app/views/joins/index.html.erb
<h1>Joins#index</h1>
<p>Find me in app/views/joins/index.html.erb</p>

app/views/joins/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for(Join.new, { controller: :joins, action: :create}) do |f| %>

      <div class="form-group">
        <ul class="list-group">
        <% Course.all.each do |course| %>
          <li class="list-group-item"><%= f.radio_button(:course_id, course.id) %> : <%= course.name %></li>
        <% end %>
        </ul>
      </div>

      <div class="form-group">
        <%= f.submit 'join', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>SpartaAssistSystem</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "https://www.google.com/jsapi" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SAS</a>
        </div>
        <% if user_signed_in? then %>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Your courses.</li>
                    <% current_user.courses.each do |course| %>
                      <li><%= link_to course.name, course %></li>
                    <% end %>
                  <li class="divider"></li>
                  <li class="dropdown-header">Create new course?</li>
                  <li><%= link_to 'コースを作成する', new_course_path  %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Signed in as <%= current_user.email %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Your Profile', user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete  %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        <% end %>
      </div>
    </div>

    <div class="container wrap">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/paper.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>SpartaAssistSystem</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/users/show.html.erb
<div class="row" style="text-align: center;">
<%= image_tag @user.image_url, style: 'text-align: center; display: inline-block' %>
</div>
<div class="row">

<p style='text-align: center; font-size: 32px;'>
<%= @user.name %>
</p>
</div>